# Generated by Django 5.2.1 on 2025-06-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_curriculum_file_course_file_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(help_text='Batch number (1, 2, 3, 4)')),
                ('title', models.CharField(help_text="e.g., 'Batch 1', 'Morning Batch'", max_length=100)),
                ('subtitle', models.CharField(default='(Mon-Fri)', help_text="e.g., '(Mon-Fri)', '(Weekends)'", max_length=100)),
                ('start_date', models.DateField(help_text='Batch start date')),
                ('start_day', models.CharField(help_text="e.g., 'Monday', '15th January'", max_length=50)),
                ('time_slot', models.CharField(help_text="e.g., '10:00 AM - 12:00 PM'", max_length=100)),
                ('duration', models.CharField(help_text="e.g., '2 hours', '3 months'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show this batch on frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_schedules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Batch Schedule',
                'verbose_name_plural': 'Batch Schedules',
                'ordering': ['batch_number'],
                'unique_together': {('course', 'batch_number')},
            },
        ),
    ]
