name: Deploy to prod

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/prod
          sudo rm -rf bigclasses.ai_finalweb
          git clone https://github.com/BigClasses-stack/bigclasses.ai_finalweb.git
          cd /home/ubuntu/prod/bigclasses.ai_finalweb
          git checkout prod
          git pull origin prod
          chmod +x deploy.sh
          ./deploy.sh